import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    { type: 'doc', id: 'index', label: 'Введение' },
    {
      type: 'category',
      label: 'Команды',
      items: [{ type: 'doc', id: 'commands/overview' }],
    },
    {
      type: 'category',
      label: 'Возможности',
      items: [{ type: 'doc', id: 'features/overview' }],
    },
    {
      type: 'category',
      label: 'Подключение',
      items: [{ type: 'autogenerated', dirName: 'setup' }],
    },    
    {
      type: 'category',
      label: 'Игровые серверы',
      items: [
        { type: 'doc', id: 'servers/css-link', label: 'Связка с сервером' },
        {
          type: 'category',
          label: 'Серверная часть',
          items: [{ type: 'autogenerated', dirName: 'servers/server' }],
        },
      ],
    },    
    { type: 'doc', id: 'faq', label: 'FAQ' },
  ],
};

export default sidebars;
