import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    { type: 'doc', id: 'index', label: 'Введение' },
    {
      type: 'category',
      label: 'Команды',
      items: [{ type: 'doc', id: 'commands/overview' }],
    },
    {
      type: 'category',
      label: 'Возможности',
      items: [
        { type: 'doc', id: 'features/overview' },
        {
          type: 'category',
          label: 'Браки',
          link: { type: 'doc', id: 'features/marriages/index' },
          items: [
            'features/marriages/commands',
            'features/marriages/how-it-works',
            'features/marriages/rules',
            'features/marriages/faq',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Подключение',
      items: [{ type: 'autogenerated', dirName: 'setup' }],
    },    
    {
      type: 'category',
      label: 'Игровые серверы',
      items: [
        { type: 'doc', id: 'servers/css-link', label: 'Связка с сервером' },
        {
          type: 'category',
          label: 'Серверная часть',
          items: [{ type: 'autogenerated', dirName: 'servers/server' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Разное',
      items: [
        { type: 'doc', id: 'fun/coolness-scale', label: 'Шкала крутости' },
      ],
    },
    { type: 'doc', id: 'faq', label: 'FAQ' },
  ],
};

export default sidebars;
